// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ORDERFOOD.Web.Models;

namespace ORDERFOOD.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201224110549_e")]
    partial class e
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("ORDERFOOD.Web.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Gạo",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Thịt",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Hoa Quả",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("ORDERFOOD.Web.Models.Food", b =>
                {
                    b.Property<int>("FoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Isdeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("ShortContent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FoodId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            FoodId = 1,
                            Address = "Hue",
                            CategoryId = 1,
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
                            Image = "https://acecookvietnam.cdn.vccloud.vn/wp-content/uploads/2017/07/590-HH-TCC.png",
                            Isdeleted = false,
                            Price = 14,
                            ShortContent = "Gạo Lứt Huế"
                        },
                        new
                        {
                            FoodId = 2,
                            Address = "Hue",
                            CategoryId = 2,
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
                            Image = "https://acecookvietnam.cdn.vccloud.vn/wp-content/uploads/2017/07/590-HH-TCC.png",
                            Isdeleted = false,
                            Price = 14,
                            ShortContent = "Gạo Lứt Huế"
                        },
                        new
                        {
                            FoodId = 3,
                            Address = "Hue",
                            CategoryId = 1,
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
                            Image = "https://acecookvietnam.cdn.vccloud.vn/wp-content/uploads/2017/07/590-HH-TCC.png",
                            Isdeleted = false,
                            Price = 14,
                            ShortContent = "Gạo Lứt Huế"
                        },
                        new
                        {
                            FoodId = 4,
                            Address = "Hue",
                            CategoryId = 3,
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
                            Image = "https://acecookvietnam.cdn.vccloud.vn/wp-content/uploads/2017/07/590-HH-TCC.png",
                            Isdeleted = false,
                            Price = 14,
                            ShortContent = "Gạo Lứt Huế"
                        },
                        new
                        {
                            FoodId = 5,
                            Address = "Hue",
                            CategoryId = 1,
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
                            Image = "https://acecookvietnam.cdn.vccloud.vn/wp-content/uploads/2017/07/590-HH-TCC.png",
                            Isdeleted = false,
                            Price = 14,
                            ShortContent = "Gạo Lứt Huế"
                        });
                });

            modelBuilder.Entity("ORDERFOOD.Web.Models.ProductTag", b =>
                {
                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("FoodId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ProductTag");
                });

            modelBuilder.Entity("ORDERFOOD.Web.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rẻ"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ngon"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bổ Khỏe"
                        });
                });

            modelBuilder.Entity("ORDERFOOD.Web.Models.Food", b =>
                {
                    b.HasOne("ORDERFOOD.Web.Models.Category", "Category")
                        .WithMany("Foods")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ORDERFOOD.Web.Models.ProductTag", b =>
                {
                    b.HasOne("ORDERFOOD.Web.Models.Food", "Food")
                        .WithMany("ProductTags")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ORDERFOOD.Web.Models.Tag", "Tag")
                        .WithMany("ProductTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ORDERFOOD.Web.Models.Category", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("ORDERFOOD.Web.Models.Food", b =>
                {
                    b.Navigation("ProductTags");
                });

            modelBuilder.Entity("ORDERFOOD.Web.Models.Tag", b =>
                {
                    b.Navigation("ProductTags");
                });
#pragma warning restore 612, 618
        }
    }
}
